# fly.toml app configuration file generated for test-llm on 2025-05-24T14:16:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-llm'
primary_region = 'fra'

[build]
  dockerfile = 'docker/Dockerfile'

[env]
  STORAGE_DIR = '/app/server/storage'
  SERVER_HOST = '0.0.0.0'
  RUNPOD_OLLAMA_URL = 'https://f3oigjgotyhqyg-11434.proxy.runpod.net'

[[mounts]]
  source = 'data_volume'
  destination = '/app/server/storage'
  initial_size = '2GB'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [services.concurrency]
    type = 'connections'
    hard_limit = 20
    soft_limit = 10

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
