# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'test-llm'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '60s'

[build]
  dockerfile = 'docker/Dockerfile'

[env]
  SERVER_HOST = '0.0.0.0'
  STORAGE_DIR = '/app/server/storage'

[[mounts]]
  source = 'data_volume'
  destination = '/app/server/storage'
  initial_size = '1GB'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [services.concurrency]
    type = 'connections'
    hard_limit = 20
    soft_limit = 10

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
